window.K2040_CONTENT={
  projects:[
    {id:"android",href:"https://kamui2040.github.io/K2040-Android-Releases/",available:true,strings:{en:{label:"Android",title:"Android Projects",description:"Official Android releases, documentation, feedback routes, and support."},de:{label:"Android",title:"Android-Projekte",description:"Offizielle Android-Veröffentlichungen, Dokumentation, Rückmeldewege und Support."},"pt-PT":{label:"Android",title:"Projetos Android",description:"Lançamentos oficiais para Android, documentação, formas de contacto e apoio."},es:{label:"Android",title:"Proyectos Android",description:"Lanzamientos oficiales de Android, documentación, vías de contacto y soporte."},fr:{label:"Android",title:"Projets Android",description:"Versions Android officielles, documentation, moyens de retour et assistance."}}},
    {id:"gaming-mods",href:"/gaming-mods/",available:true,strings:{en:{label:"Gaming",title:"Gaming Mods",description:"Released game mods, official downloads, compatibility information, and development previews."},de:{label:"Gaming",title:"Spiele-Mods",description:"Veröffentlichte Spiele-Mods, offizielle Downloads, Kompatibilitätsinformationen und Entwicklungsvorschauen."},"pt-PT":{label:"Jogos",title:"Mods de Jogos",description:"Mods de jogos publicados, transferências oficiais, informações de compatibilidade e antevisões de desenvolvimento."},es:{label:"Juegos",title:"Mods de Juegos",description:"Mods de juegos publicados, descargas oficiales, información de compatibilidad y avances de desarrollo."},fr:{label:"Jeux",title:"Mods de Jeux",description:"Mods de jeux publiés, téléchargements officiels, informations de compatibilité et aperçus du développement."}}}
  ],
  updates:[
    {id:"gaming-mods-page",date:"2026-06-22",href:"/gaming-mods/",strings:{en:{category:"Gaming",title:"Gaming Mods page added",summary:"Released mods and active development projects now have a dedicated multilingual gateway."},de:{category:"Gaming",title:"Seite für Spiele-Mods hinzugefügt",summary:"Veröffentlichte Mods und aktive Entwicklungsprojekte haben nun einen eigenen mehrsprachigen Einstiegspunkt."},"pt-PT":{category:"Jogos",title:"Página de Mods de Jogos adicionada",summary:"Os mods publicados e os projetos em desenvolvimento ativo têm agora um portal multilingue dedicado."},es:{category:"Juegos",title:"Página de Mods de Juegos añadida",summary:"Los mods publicados y los proyectos en desarrollo activo cuentan ahora con un portal multilingüe dedicado."},fr:{category:"Jeux",title:"Page des Mods de Jeux ajoutée",summary:"Les mods publiés et les projets en développement actif disposent désormais d’un portail multilingue dédié."}}},
    {id:"android-hub",date:"2026-06-22",href:"https://kamui2040.github.io/K2040-Android-Releases/",strings:{en:{category:"Android",title:"The Android project hub is now multilingual",summary:"The dedicated Android page now supports a single-language interface, automatic language detection, and persistent light and dark themes."},de:{category:"Android",title:"Der Android-Projekthub ist jetzt mehrsprachig",summary:"Die eigene Android-Seite unterstützt nun eine einsprachige Oberfläche, automatische Spracherkennung sowie dauerhafte helle und dunkle Designs."},"pt-PT":{category:"Android",title:"O centro de projetos Android é agora multilingue",summary:"A página Android dedicada passa a ter uma interface num único idioma, deteção automática do idioma e temas claro e escuro persistentes."},es:{category:"Android",title:"El centro de proyectos Android ya es multilingüe",summary:"La página dedicada a Android incorpora una interfaz de un solo idioma, detección automática del idioma y temas claro y oscuro persistentes."},fr:{category:"Android",title:"Le portail des projets Android est désormais multilingue",summary:"La page Android dédiée propose une interface dans une seule langue, la détection automatique de la langue et des thèmes clair et sombre persistants."}}},
    {id:"frontpage",date:"2026-06-22",href:null,strings:{en:{category:"Website",title:"The shared K2040 gateway is available",summary:"The front page now connects Android projects, gaming mods, support links, and compact project updates."},de:{category:"Webseite",title:"Der gemeinsame K2040-Einstiegspunkt ist verfügbar",summary:"Die Startseite verbindet nun Android-Projekte, Spiele-Mods, Supportlinks und kompakte Projektupdates."},"pt-PT":{category:"Website",title:"O portal comum K2040 está disponível",summary:"A página inicial liga agora projetos Android, mods de jogos, ligações de apoio e atualizações compactas."},es:{category:"Sitio web",title:"El portal común de K2040 está disponible",summary:"La página principal conecta ahora proyectos Android, mods de juegos, enlaces de soporte y actualizaciones breves."},fr:{category:"Site web",title:"Le portail K2040 commun est disponible",summary:"La page d’accueil relie désormais les projets Android, les mods de jeux, les liens d’assistance et de brèves actualités."}}}
  ]
};
