window.K2040_CONTENT={
  projects:[
    {id:"android",href:"https://kamui2040.github.io/K2040-Android-Releases/",available:true,strings:{en:{label:"Android",title:"Android Projects",description:"Official Android releases, documentation, feedback routes, and support."},de:{label:"Android",title:"Android-Projekte",description:"Offizielle Android-Veröffentlichungen, Dokumentation, Rückmeldewege und Support."},"pt-PT":{label:"Android",title:"Projetos Android",description:"Lançamentos oficiais para Android, documentação, formas de contacto e apoio."},es:{label:"Android",title:"Proyectos Android",description:"Lanzamientos oficiales de Android, documentación, vías de contacto y soporte."},fr:{label:"Android",title:"Projets Android",description:"Versions Android officielles, documentation, moyens de retour et assistance."}}},
    {id:"gaming-mods",href:"/gaming-mods/",available:false,strings:{en:{label:"Gaming",title:"Gaming Mods",description:"Game modifications, compatibility information, downloads, and project notes."},de:{label:"Gaming",title:"Spiele-Mods",description:"Spielmodifikationen, Kompatibilitätsinformationen, Downloads und Projekthinweise."},"pt-PT":{label:"Jogos",title:"Mods de Jogos",description:"Modificações de jogos, informações de compatibilidade, transferências e notas de projeto."},es:{label:"Juegos",title:"Mods de Juegos",description:"Modificaciones de juegos, información de compatibilidad, descargas y notas de proyecto."},fr:{label:"Jeux",title:"Mods de Jeux",description:"Modifications de jeux, informations de compatibilité, téléchargements et notes de projet."}}}
  ],
  updates:[
    {id:"android-hub",date:"2026-06-22",href:"https://kamui2040.github.io/K2040-Android-Releases/",strings:{en:{category:"Android",title:"The Android project hub is now multilingual",summary:"The dedicated Android page now supports a single-language interface, automatic language detection, and persistent light and dark themes."},de:{category:"Android",title:"Der Android-Projekthub ist jetzt mehrsprachig",summary:"Die eigene Android-Seite unterstützt nun eine einsprachige Oberfläche, automatische Spracherkennung sowie dauerhafte helle und dunkle Designs."},"pt-PT":{category:"Android",title:"O centro de projetos Android é agora multilingue",summary:"A página Android dedicada passa a ter uma interface num único idioma, deteção automática do idioma e temas claro e escuro persistentes."},es:{category:"Android",title:"El centro de proyectos Android ya es multilingüe",summary:"La página dedicada a Android incorpora una interfaz de un solo idioma, detección automática del idioma y temas claro y oscuro persistentes."},fr:{category:"Android",title:"Le portail des projets Android est désormais multilingue",summary:"La page Android dédiée propose une interface dans une seule langue, la détection automatique de la langue et des thèmes clair et sombre persistants."}}},
    {id:"frontpage",date:"2026-06-22",href:null,strings:{en:{category:"Website",title:"The shared K2040 gateway is being prepared",summary:"The new front page connects Android projects, future gaming-mod pages, support links, and compact project updates."},de:{category:"Webseite",title:"Der gemeinsame K2040-Einstiegspunkt wird vorbereitet",summary:"Die neue Startseite verbindet Android-Projekte, zukünftige Seiten für Spiele-Mods, Supportlinks und kompakte Projektupdates."},"pt-PT":{category:"Website",title:"O portal comum K2040 está a ser preparado",summary:"A nova página inicial liga projetos Android, futuras páginas de mods de jogos, ligações de apoio e atualizações compactas."},es:{category:"Sitio web",title:"Se está preparando el portal común de K2040",summary:"La nueva página principal conecta proyectos Android, futuras páginas de mods de juegos, enlaces de soporte y actualizaciones breves."},fr:{category:"Site web",title:"Le portail K2040 commun est en préparation",summary:"La nouvelle page d’accueil relie les projets Android, les futures pages de mods de jeux, les liens d’assistance et de brèves actualités."}}}
  ]
};
