(() => {
  "use strict";
  const languageKey="k2040-language";
  const supported=["en","de","pt-PT","es","fr"];
  const labels={
    en:{menu:"K2040 navigation",home:"Home",android:"Android Projects",gaming:"Gaming Mods",projectAreas:"Project Areas",news:"News",about:"About",androidHome:"Android Home",apps:"Apps",updates:"Updates",modsHome:"Mods Home",modProjects:"Mod Projects",newsEyebrow:"Latest",newsTitle:"News",newsDescription:"Meaningful public changes and the latest updates from K2040 projects.",viewAll:"View all news",aboutDescription:"A central place for K2040 apps, game mods, tools, releases, documentation, and public updates.",newsMeta:"News · K2040 Projects"},
    de:{menu:"K2040-Navigation",home:"Home",android:"Android-Projekte",gaming:"Gaming Mods",projectAreas:"Projektbereiche",news:"News",about:"Info",androidHome:"Android-Startseite",apps:"Apps",updates:"Updates",modsHome:"Mods-Startseite",modProjects:"Mod-Projekte",newsEyebrow:"Neu",newsTitle:"News",newsDescription:"Wichtige öffentliche Änderungen und die neuesten Updates der K2040-Projekte.",viewAll:"Alle News anzeigen",aboutDescription:"Ein zentraler Ort für K2040-Apps, Spiele-Mods, Tools, Veröffentlichungen, Dokumentation und öffentliche Updates.",newsMeta:"News · K2040 Projects"},
    "pt-PT":{menu:"Navegação K2040",home:"Início",android:"Projetos Android",gaming:"Gaming Mods",projectAreas:"Áreas de projetos",news:"Notícias",about:"Sobre",androidHome:"Início Android",apps:"Apps",updates:"Atualizações",modsHome:"Início dos Mods",modProjects:"Projetos de Mods",newsEyebrow:"Novidades",newsTitle:"Notícias",newsDescription:"Alterações públicas importantes e as atualizações mais recentes dos projetos K2040.",viewAll:"Ver todas as notícias",aboutDescription:"Um local central para apps K2040, mods de jogos, ferramentas, lançamentos, documentação e atualizações públicas.",newsMeta:"Notícias · K2040 Projects"},
    es:{menu:"Navegación K2040",home:"Inicio",android:"Proyectos Android",gaming:"Gaming Mods",projectAreas:"Áreas de proyectos",news:"Noticias",about:"Acerca de",androidHome:"Inicio Android",apps:"Apps",updates:"Actualizaciones",modsHome:"Inicio de Mods",modProjects:"Proyectos de Mods",newsEyebrow:"Novedades",newsTitle:"Noticias",newsDescription:"Cambios públicos importantes y las últimas actualizaciones de los proyectos K2040.",viewAll:"Ver todas las noticias",aboutDescription:"Un lugar central para aplicaciones K2040, mods de juegos, herramientas, lanzamientos, documentación y actualizaciones públicas.",newsMeta:"Noticias · K2040 Projects"},
    fr:{menu:"Navigation K2040",home:"Accueil",android:"Projets Android",gaming:"Gaming Mods",projectAreas:"Domaines de projets",news:"Actualités",about:"À propos",androidHome:"Accueil Android",apps:"Apps",updates:"Mises à jour",modsHome:"Accueil des Mods",modProjects:"Projets de Mods",newsEyebrow:"Nouveautés",newsTitle:"Actualités",newsDescription:"Les changements publics importants et les dernières mises à jour des projets K2040.",viewAll:"Voir toutes les actualités",aboutDescription:"Un point central pour les applications K2040, les mods de jeux, les outils, les versions, la documentation et les mises à jour publiques.",newsMeta:"Actualités · K2040 Projects"}
  };
  const normalize=(value)=>{const v=(value||"").toLowerCase();if(v.startsWith("de"))return"de";if(v.startsWith("pt"))return"pt-PT";if(v.startsWith("es"))return"es";if(v.startsWith("fr"))return"fr";return"en"};
  const current=()=>{try{const saved=localStorage.getItem(languageKey);if(supported.includes(saved))return saved}catch{}return normalize(document.documentElement.lang||navigator.language)};
  let language=current();
  let combined=[...(window.K2040_CONTENT?.updates||[])];
  const localStrings=(entry)=>entry?.strings?.[language]||entry?.strings?.en||{};
  const applyLabels=()=>{const copy=labels[language]||labels.en;document.querySelectorAll("[data-home-i18n]").forEach((el)=>{const value=copy[el.dataset.homeI18n];if(value)el.textContent=value});document.querySelectorAll("[data-home-aria]").forEach((el)=>{const value=copy[el.dataset.homeAria];if(value)el.setAttribute("aria-label",value)});if(document.body.classList.contains("news-page")){document.title=copy.newsMeta;const meta=document.querySelector('meta[name="description"]');if(meta)meta.content=copy.newsDescription}};
  const updateTime=(entry)=>{const value=Date.parse(`${entry?.date||""}T00:00:00Z`);return Number.isNaN(value)?null:value};
  const sorted=()=>combined.map((entry,index)=>({entry,index,time:updateTime(entry)})).sort((a,b)=>{if(a.time===null&&b.time===null)return a.index-b.index;if(a.time===null)return 1;if(b.time===null)return-1;if(a.time!==b.time)return b.time-a.time;return a.index-b.index}).map(({entry})=>entry);
  const render=()=>{const list=document.querySelector("[data-update-list]");const template=document.querySelector("#update-card-template");if(!list||!template)return;const all=document.body.classList.contains("news-page");const entries=all?sorted():sorted().slice(0,5);list.replaceChildren();for(const update of entries){const strings=localStrings(update);const fragment=template.content.cloneNode(true);const time=fragment.querySelector("[data-update-date]");time.dateTime=update.date;time.textContent=new Intl.DateTimeFormat(language,{year:"numeric",month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(`${update.date}T00:00:00Z`));fragment.querySelector("[data-update-category]").textContent=strings.category||"";fragment.querySelector("[data-update-title]").textContent=strings.title||"";fragment.querySelector("[data-update-summary]").textContent=strings.summary||"";const link=fragment.querySelector("[data-update-link]");if(update.href){link.href=update.href;link.textContent=update.href.includes("nexusmods.com")?"Nexus Mods":update.href.includes("github.com")?"GitHub":(window.K2040_TRANSLATIONS?.[language]?.actions?.readMore||"Read more")}else link.remove();list.append(fragment)}};
  const loadScriptData=async(url,selector)=>{const response=await fetch(url,{cache:"no-cache"});if(!response.ok)throw new Error(`${response.status} ${url}`);const source=await response.text();const sandbox={};new Function("window",`"use strict";\n${source}`)(sandbox);const value=selector(sandbox);return Array.isArray(value)?value:[]};
  const loadFeeds=async()=>{
    const home=[...(window.K2040_CONTENT?.updates||[])];
    const fullNews=document.body.classList.contains("news-page");
    const requests=[
      loadScriptData("/K2040-Android-Releases/updates/latest.js",(box)=>box.K2040_CONTENT?.updates)
    ];
    if(fullNews){requests.push(loadScriptData("/K2040-Android-Releases/updates/archive-2026.js",(box)=>box.K2040_CONTENT?.updates));}
    requests.push(loadScriptData("/K2040-Gaming-Mods/updates/2026.js",(box)=>box.K2040_GAMING_UPDATES));
    const results=await Promise.allSettled(requests);
    const androidLatest=results[0].status==="fulfilled"?results[0].value:[];
    let androidArchive=[];
    let gamingResult;
    if(fullNews){androidArchive=results[1].status==="fulfilled"?results[1].value:[];gamingResult=results[2];}else{gamingResult=results[1];}
    const gaming=gamingResult?.status==="fulfilled"?gamingResult.value:[];
    combined=[...home,...androidLatest,...androidArchive,...gaming];
    render();
  };
  const initMenu=(menu)=>{const items=[...menu.querySelectorAll("[data-global-menu-item]")];const position=(item)=>{item.classList.remove("global-menu-item--flip");if(!item.open||innerWidth<=760)return;requestAnimationFrame(()=>{const panel=menu.querySelector(".global-menu-panel"),sub=item.querySelector(".global-menu-submenu");if(!panel||!sub)return;const rect=panel.getBoundingClientRect(),width=sub.offsetWidth||245,gap=9,margin=16;const fitsRight=rect.right+gap+width<=innerWidth-margin;const fitsLeft=rect.left-gap-width>=margin;item.classList.toggle("global-menu-item--flip",!fitsRight&&fitsLeft)})};items.forEach((item)=>item.addEventListener("toggle",()=>{if(item.open){items.forEach((other)=>{if(other!==item)other.open=false});position(item)}}));menu.addEventListener("toggle",()=>{if(!menu.open)items.forEach((item)=>item.open=false)});addEventListener("resize",()=>items.forEach(position),{passive:true})};
  const init=()=>{applyLabels();document.querySelectorAll("[data-global-menu]").forEach(initMenu);document.addEventListener("click",(event)=>document.querySelectorAll("[data-global-menu][open]").forEach((menu)=>{if(!menu.contains(event.target))menu.open=false}));const select=document.querySelector("[data-language-select]");select?.addEventListener("change",()=>{if(supported.includes(select.value)){language=select.value;applyLabels();render()}});render();loadFeeds().catch(()=>render())};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
