window.K2040_TRANSLATIONS = {
  en: {
    meta: { title: "K2040 Gaming Mods", description: "Released K2040 game mods, official download links, and compatibility notes." },
    controls: { language: "Language", dark: "Dark", light: "Light", switchToDark: "Switch to dark theme", switchToLight: "Switch to light theme" },
    nav: { projects: "Projects", browseProjects: "Browse projects", games: "Games", downloads: "Downloads", updates: "Updates", about: "About" },
    menu: { dirdeDescription: "Ultimate Edition Mod Menu · Linux", ecoDescription: "AiO installer and individual patches", xeditDescription: "FO4Edit export utility" },
    landing: { heroEyebrow: "Gaming Mods", heroDescription: "Open Source game mods, tools, and enhancements.", exploreProjects: "Explore projects", viewGithub: "GitHub profile", featuredEyebrow: "Featured project", featuredDescription: "AiO and individual compatibility patches for Fallout 4 quick-menu setups.", featuredCopy: "One place for the AiO installer and individual optional patches, with separate official links and changelogs.", viewProject: "View project", aboutEyebrow: "K2040 Projects", aboutTitle: "About", aboutDescription: "Open Source game mods and tools with official download links and project-specific documentation." },
    projects: { eyebrow: "Released", title: "Mod Projects", description: "Choose a project to see its overview, downloads, changelog, and screenshots." },
    updates: { eyebrow: "Latest", title: "Mod Updates", description: "New releases and important project updates." },
    actions: { open: "Open project", readMore: "Read more" }, status: { available: "Released" }, tags: { linux: "Linux", gameplay: "Gameplay", windows: "Windows", tools: "Tools", aio: "AiO", singlePatches: "Single patches", released: "Released" },
    detail: { chooseOptionEyebrow: "Choose an option", downloadsChangelogs: "Downloads and changelogs", chooseOptionDescription: "Choose the installation option that fits your load order.", overviewEyebrow: "Overview", aboutTitle: "About this project", featuresEyebrow: "Included", featuresTitle: "Features", officialLinksTitle: "Official links", officialLinksDescription: "Use the official project pages for current files and installation details.", galleryEyebrow: "Gallery", screenshotsTitle: "Screenshots", screenshotsDescription: "Project screenshots and interface previews.", changelogEyebrow: "Changelog", latestRelease: "Latest release", nexusMods: "Nexus Mods", githubRelease: "GitHub release", openNexus: "Open Nexus Mods", openOriginal: "Open original mod", openGithub: "Open GitHub release", changelogTitle: "Changelog", closeScreenshot: "Close full-screen screenshot", openFullSize: "Open full size", projectArtworkSuffix: "project artwork" },
    footer: { linksLabel: "K2040 links", home: "Home", android: "Android Projects", gaming: "Gaming Mods", github: "GitHub", note: "Official Nexus Mods pages remain the authoritative source for released files." }
  },
  de: {
    meta: { title: "K2040 Gaming Mods", description: "Veröffentlichte K2040 Gaming Mods, offizielle Downloads und Hinweise zur Kompatibilität." },
    controls: { language: "Sprache", dark: "Dunkel", light: "Hell", switchToDark: "Zum dunklen Design wechseln", switchToLight: "Zum hellen Design wechseln" },
    nav: { projects: "Projekte", browseProjects: "Projekte durchsuchen", games: "Spiele", downloads: "Downloads", updates: "Updates", about: "Info" },
    menu: { dirdeDescription: "Ultimate Edition Mod Menu · Linux", ecoDescription: "AiO-Installer und einzelne Patches", xeditDescription: "Export-Tool für FO4Edit" },
    landing: { heroEyebrow: "Gaming Mods", heroDescription: "Open Source Mods, Tools und Erweiterungen für Spiele.", exploreProjects: "Projekte entdecken", viewGithub: "GitHub-Profil", featuredEyebrow: "Im Fokus", featuredDescription: "AiO-Installer und einzelne Kompatibilitätspatches für das Quick Menu in Fallout 4.", featuredCopy: "Der AiO-Installer und alle optionalen Einzelpatches an einem Ort – mit getrennten offiziellen Links und Changelogs.", viewProject: "Projekt ansehen", aboutEyebrow: "K2040 Projekte", aboutTitle: "Info", aboutDescription: "Open Source Mods und Tools mit offiziellen Downloads und eigener Dokumentation für jedes Projekt." },
    projects: { eyebrow: "Veröffentlicht", title: "Mod-Projekte", description: "Wähle ein Projekt aus, um Übersicht, Downloads, Changelog und Screenshots zu sehen." },
    updates: { eyebrow: "Neu", title: "Mod-Updates", description: "Neue Releases und wichtige Projekt-Updates." },
    actions: { open: "Projekt öffnen", readMore: "Mehr erfahren" }, status: { available: "Veröffentlicht" }, tags: { linux: "Linux", gameplay: "Gameplay", windows: "Windows", tools: "Tools", aio: "AiO", singlePatches: "Einzelpatches", released: "Veröffentlicht" },
    detail: { chooseOptionEyebrow: "Option wählen", downloadsChangelogs: "Downloads und Changelogs", chooseOptionDescription: "Wähle die passende Installationsoption für deine Load Order.", overviewEyebrow: "Übersicht", aboutTitle: "Über dieses Projekt", featuresEyebrow: "Enthalten", featuresTitle: "Features", officialLinksTitle: "Offizielle Links", officialLinksDescription: "Aktuelle Dateien und Installationshinweise findest du auf den offiziellen Projektseiten.", galleryEyebrow: "Galerie", screenshotsTitle: "Screenshots", screenshotsDescription: "Screenshots und Vorschauen der Projektoberfläche.", changelogEyebrow: "Changelog", latestRelease: "Neuester Release", nexusMods: "Nexus Mods", githubRelease: "GitHub Release", openNexus: "Nexus Mods öffnen", openOriginal: "Original-Mod öffnen", openGithub: "GitHub Release öffnen", changelogTitle: "Changelog", closeScreenshot: "Vollbild-Screenshot schließen", openFullSize: "In voller Größe öffnen", projectArtworkSuffix: "Projektgrafik" },
    footer: { linksLabel: "K2040 Links", home: "Home", android: "Android-Projekte", gaming: "Gaming Mods", github: "GitHub", note: "Die offiziellen Nexus Mods Seiten sind die maßgebliche Quelle für veröffentlichte Dateien." }
  },
  "pt-PT": {
    meta: { title: "K2040 Gaming Mods", description: "Gaming Mods K2040 publicados, downloads oficiais e notas de compatibilidade." },
    controls: { language: "Idioma", dark: "Escuro", light: "Claro", switchToDark: "Mudar para o tema escuro", switchToLight: "Mudar para o tema claro" },
    nav: { projects: "Projetos", browseProjects: "Explorar projetos", games: "Jogos", downloads: "Downloads", updates: "Atualizações", about: "Sobre" },
    menu: { dirdeDescription: "Ultimate Edition Mod Menu · Linux", ecoDescription: "Instalador AiO e patches individuais", xeditDescription: "Ferramenta de exportação para FO4Edit" },
    landing: { heroEyebrow: "Gaming Mods", heroDescription: "Mods, ferramentas e melhorias Open Source.", exploreProjects: "Explorar projetos", viewGithub: "Perfil no GitHub", featuredEyebrow: "Projeto em destaque", featuredDescription: "Instalador AiO e patches de compatibilidade individuais para o quick menu de Fallout 4.", featuredCopy: "O instalador AiO e os patches opcionais individuais num só lugar, com links oficiais e changelogs separados.", viewProject: "Ver projeto", aboutEyebrow: "Projetos K2040", aboutTitle: "Sobre", aboutDescription: "Mods e ferramentas Open Source com downloads oficiais e documentação própria para cada projeto." },
    projects: { eyebrow: "Publicados", title: "Projetos de Mods", description: "Escolha um projeto para ver o resumo, os downloads, o changelog e as capturas de ecrã." },
    updates: { eyebrow: "Novidades", title: "Atualizações dos Mods", description: "Novos releases e atualizações importantes dos projetos." },
    actions: { open: "Abrir projeto", readMore: "Saber mais" }, status: { available: "Publicado" }, tags: { linux: "Linux", gameplay: "Gameplay", windows: "Windows", tools: "Ferramentas", aio: "AiO", singlePatches: "Patches individuais", released: "Publicado" },
    detail: { chooseOptionEyebrow: "Escolher opção", downloadsChangelogs: "Downloads e changelogs", chooseOptionDescription: "Escolha a opção de instalação adequada à sua load order.", overviewEyebrow: "Resumo", aboutTitle: "Sobre este projeto", featuresEyebrow: "Incluído", featuresTitle: "Funcionalidades", officialLinksTitle: "Links oficiais", officialLinksDescription: "Consulte as páginas oficiais dos projetos para obter os ficheiros atuais e as instruções de instalação.", galleryEyebrow: "Galeria", screenshotsTitle: "Capturas de ecrã", screenshotsDescription: "Capturas de ecrã e pré-visualizações da interface do projeto.", changelogEyebrow: "Changelog", latestRelease: "Release mais recente", nexusMods: "Nexus Mods", githubRelease: "Release no GitHub", openNexus: "Abrir Nexus Mods", openOriginal: "Abrir mod original", openGithub: "Abrir release no GitHub", changelogTitle: "Changelog", closeScreenshot: "Fechar captura de ecrã em ecrã inteiro", openFullSize: "Abrir no tamanho original", projectArtworkSuffix: "imagem do projeto" },
    footer: { linksLabel: "Links K2040", home: "Início", android: "Projetos Android", gaming: "Gaming Mods", github: "GitHub", note: "As páginas oficiais no Nexus Mods são a fonte principal dos ficheiros publicados." }
  },
  es: {
    meta: { title: "K2040 Gaming Mods", description: "Gaming Mods K2040 publicados, descargas oficiales y notas de compatibilidad." },
    controls: { language: "Idioma", dark: "Oscuro", light: "Claro", switchToDark: "Cambiar al tema oscuro", switchToLight: "Cambiar al tema claro" },
    nav: { projects: "Proyectos", browseProjects: "Explorar proyectos", games: "Juegos", downloads: "Descargas", updates: "Actualizaciones", about: "Acerca de" },
    menu: { dirdeDescription: "Ultimate Edition Mod Menu · Linux", ecoDescription: "Instalador AiO y parches individuales", xeditDescription: "Herramienta de exportación para FO4Edit" },
    landing: { heroEyebrow: "Gaming Mods", heroDescription: "Mods, herramientas y mejoras Open Source.", exploreProjects: "Explorar proyectos", viewGithub: "Perfil de GitHub", featuredEyebrow: "Proyecto destacado", featuredDescription: "Instalador AiO y parches de compatibilidad individuales para el quick menu de Fallout 4.", featuredCopy: "El instalador AiO y los parches opcionales individuales en un solo lugar, con enlaces oficiales y changelogs separados.", viewProject: "Ver proyecto", aboutEyebrow: "Proyectos K2040", aboutTitle: "Acerca de", aboutDescription: "Mods y herramientas Open Source con descargas oficiales y documentación específica para cada proyecto." },
    projects: { eyebrow: "Publicados", title: "Proyectos de Mods", description: "Elige un proyecto para ver su resumen, descargas, changelog y capturas de pantalla." },
    updates: { eyebrow: "Novedades", title: "Actualizaciones de Mods", description: "Nuevos lanzamientos y actualizaciones importantes de los proyectos." },
    actions: { open: "Abrir proyecto", readMore: "Más información" }, status: { available: "Publicado" }, tags: { linux: "Linux", gameplay: "Gameplay", windows: "Windows", tools: "Herramientas", aio: "AiO", singlePatches: "Parches individuales", released: "Publicado" },
    detail: { chooseOptionEyebrow: "Elige una opción", downloadsChangelogs: "Descargas y changelogs", chooseOptionDescription: "Elige la opción de instalación adecuada para tu load order.", overviewEyebrow: "Resumen", aboutTitle: "Acerca de este proyecto", featuresEyebrow: "Incluido", featuresTitle: "Funciones", officialLinksTitle: "Enlaces oficiales", officialLinksDescription: "Consulta las páginas oficiales de los proyectos para obtener los archivos actuales y las instrucciones de instalación.", galleryEyebrow: "Galería", screenshotsTitle: "Capturas de pantalla", screenshotsDescription: "Capturas de pantalla y vistas previas de la interfaz del proyecto.", changelogEyebrow: "Changelog", latestRelease: "Último lanzamiento", nexusMods: "Nexus Mods", githubRelease: "Lanzamiento en GitHub", openNexus: "Abrir Nexus Mods", openOriginal: "Abrir mod original", openGithub: "Abrir lanzamiento en GitHub", changelogTitle: "Changelog", closeScreenshot: "Cerrar captura a pantalla completa", openFullSize: "Abrir a tamaño completo", projectArtworkSuffix: "imagen del proyecto" },
    footer: { linksLabel: "Enlaces de K2040", home: "Inicio", android: "Proyectos Android", gaming: "Gaming Mods", github: "GitHub", note: "Las páginas oficiales de Nexus Mods son la fuente principal de los archivos publicados." }
  },
  fr: {
    meta: { title: "K2040 Gaming Mods", description: "Gaming Mods K2040 publiés, téléchargements officiels et notes de compatibilité." },
    controls: { language: "Langue", dark: "Sombre", light: "Clair", switchToDark: "Passer au thème sombre", switchToLight: "Passer au thème clair" },
    nav: { projects: "Projets", browseProjects: "Parcourir les projets", games: "Jeux", downloads: "Téléchargements", updates: "Mises à jour", about: "À propos" },
    menu: { dirdeDescription: "Ultimate Edition Mod Menu · Linux", ecoDescription: "Installateur AiO et patchs individuels", xeditDescription: "Outil d’export pour FO4Edit" },
    landing: { heroEyebrow: "Gaming Mods", heroDescription: "Des mods, des outils et des améliorations Open Source.", exploreProjects: "Parcourir les projets", viewGithub: "Profil GitHub", featuredEyebrow: "Projet à la une", featuredDescription: "Installateur AiO et patchs de compatibilité individuels pour le quick menu de Fallout 4.", featuredCopy: "L’installateur AiO et les patchs individuels facultatifs au même endroit, avec des liens officiels et des changelogs séparés.", viewProject: "Voir le projet", aboutEyebrow: "Projets K2040", aboutTitle: "À propos", aboutDescription: "Des mods et des outils Open Source avec des téléchargements officiels et une documentation propre à chaque projet." },
    projects: { eyebrow: "Publiés", title: "Projets de Mods", description: "Choisissez un projet pour voir sa présentation, ses téléchargements, son changelog et ses captures d’écran." },
    updates: { eyebrow: "Nouveautés", title: "Mises à jour des Mods", description: "Nouvelles versions et mises à jour importantes des projets." },
    actions: { open: "Ouvrir le projet", readMore: "En savoir plus" }, status: { available: "Publié" }, tags: { linux: "Linux", gameplay: "Gameplay", windows: "Windows", tools: "Outils", aio: "AiO", singlePatches: "Patchs individuels", released: "Publié" },
    detail: { chooseOptionEyebrow: "Choisir une option", downloadsChangelogs: "Téléchargements et changelogs", chooseOptionDescription: "Choisissez l’option d’installation adaptée à votre load order.", overviewEyebrow: "Présentation", aboutTitle: "À propos de ce projet", featuresEyebrow: "Inclus", featuresTitle: "Fonctionnalités", officialLinksTitle: "Liens officiels", officialLinksDescription: "Consultez les pages officielles des projets pour obtenir les fichiers actuels et les instructions d’installation.", galleryEyebrow: "Galerie", screenshotsTitle: "Captures d’écran", screenshotsDescription: "Captures d’écran et aperçus de l’interface du projet.", changelogEyebrow: "Changelog", latestRelease: "Dernière version", nexusMods: "Nexus Mods", githubRelease: "Version GitHub", openNexus: "Ouvrir Nexus Mods", openOriginal: "Ouvrir le mod original", openGithub: "Ouvrir la version GitHub", changelogTitle: "Changelog", closeScreenshot: "Fermer la capture en plein écran", openFullSize: "Ouvrir en taille réelle", projectArtworkSuffix: "illustration du projet" },
    footer: { linksLabel: "Liens K2040", home: "Accueil", android: "Projets Android", gaming: "Gaming Mods", github: "GitHub", note: "Les pages officielles Nexus Mods sont la source de référence pour les fichiers publiés." }
  }
};
